import type { Metadata } from 'next';
import './globals.css';
import React from 'react';
import Header from "@/components/Header";
import { roboto } from "@/app/fonts";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Currency exchanger",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} w-full h-screen flex flex-col`}>
        <Header />
        <main className='flex-auto'>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
